version: '3'
services:
  keymanager:
    image: rizkimufrizal/wso2-jdk:latest
    command: tail -f /dev/null 
    volumes:
      - .:/home
    ports:
    - "9443:9443"
    networks:
      default:

  apimanagement:
    image: rizkimufrizal/wso2-jdk:latest
    command: tail -f /dev/null
    volumes:
      - .:/home
    ports:
    - "9444:9444"
    - "9445:9445"
    networks:
      default:

  gateway:
    image: rizkimufrizal/wso2-jdk:latest
    command: tail -f /dev/null
    volumes:
      - .:/home
    ports:
    - "9446:9446"
    - "8246:8246"
    - "8283:8283"
    networks:
      default:

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: root
    networks:
      default:

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

networks:
  default:
